### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by aaani** [hapijs/good-squeeze#17]
I found massive memory leaks on using `good-squeeze`. This is what my `good` config looks like -

```
server.register({
    register: require('good'),
    options: {
        ops: false, //disable ops monitoring
        reporters: {
            requestsTracker: [
                {
                    module: 'good-squeeze',
                    name: 'Squeeze',
                    args: [{
                        response: '*'
                    }]
                }
            ]
        }
    }
}, function(err) {
    if (err) {
        return console.log(err);
    }
});
```

and this is what the heapdumps look like - 
![image](https://cloud.githubusercontent.com/assets/3347504/19442315/89185e58-944e-11e6-9901-687c38a11687.png)

When there are no requests to the server, the memory usage us 12.2MB, I bombarded this app with requests using Seiege, and in the end the memory usage reaches 47.8MB. It is never able to release all the allocated memory (I expect it to get back to 12.2MB).
I repeated the same experiment by removing `good-squeeze` from `reporters.requestsTracker` above, and in that case all the memory is released, and it gets back to 12MB. I get the same results when I completely get rid of the `good` module.

This is what my app.js looks like - 

```
'use strict';

const Hapi = require('hapi');

// Create a server with a host and port
const server = new Hapi.Server();
server.connection({ 
    host: 'localhost', 
    port: 8000 
});

// Add the route
server.route({
    method: 'GET',
    path:'/hello', 
    handler: function (request, reply) {
        console.log('responding...');
        return reply({"0":"hello", "1": "world"});
    }
});

// report on some hapi server events
server.register({
    register: require('good'),
    options: {
        ops: false, //disable ops monitoring
        reporters: {
            requestsTracker: [
                {
                    module: 'good-squeeze',
                    name: 'Squeeze',
                    args: [{
                        //Information about incoming requests and the response.
                        //This maps to either the "response" or "tail" event emitted from hapi servers
                        //https://github.com/hapijs/good/blob/master/API.md#event-types
                        response: '*'
                    }]
                }
            ]
        }
    }
}, function(err) {
    if (err) {
        return console.log(err);
    }
});

// Start the server
server.start((err) => {

    if (err) {
        throw err;
    }
    console.log('Server running at:', server.info.uri);
});
```

and this is my `package.json`

```
{
  "dependencies": {
    "good": "^7.0.2",
    "good-squeeze": "^5.0.0",
    "hapi": "^15.1.1"
  }
}
```

**Comment by arb** [comment]
You didn't provide a write stream to WRITE things to, so the internal node stream mechanics are just going to keep buffering up the chunks.

**Comment by aaani** [comment]
Unfortunately I don't know enough about Streams. My goal is to send data about requests to our custom monitoring service. For that I developed our own plugin modelled after - https://github.com/hapijs/good/blob/master/test/fixtures/reporters.js#L5. Even with it plugged in after `good-squeeze` I get memory leaks. Could you please elaborate on how to `provide a write stream to WRITE things`? Or is there anyway the buffer could be cleared periodically?

**Comment by arb** [comment]
That's a transform stream. To write things, you need to use a write stream.

Check https://github.com/hapijs/good-http for a very basic example.
