### ISSUE TITLE
Events without tags are being excluded when they shouldn't

### ISSUE THREAD

**Issue by benleen** [hapijs/good-squeeze#18]
When the include filter accepts all events (which implies also events without tags) & when exclude filter are defined, there's a bug that events without tags are being excluded even though they shouldn't.

**Comment by arb** [comment]
I'm not sure this is a bug... How did this work before on the previous major version of this module?

**Comment by benleen** [comment]
It's a really specific bug related tot he combination of having exclude tags defined and not having tags.

For include in the past (and now still) this has always been implicit; as soon as you defined 1 tag to filter, you were immediately disregarding log entries that had no tags as well.

Since excluding is the inverse it's slightly different hence the bug and my PR.

An interesting takeaway is the fact that there's no way to explicitly target log entries without tags defined for either exclude or include. Not that that is a likely use case for our consumers.
