### ISSUE TITLE
Exclude response-logging on certain routes

### ISSUE THREAD

**Issue by mattii** [hapijs/good-squeeze#20]
Is there a way to exclude certain routes from response-events, based on the path or route-tags?

**Comment by arb** [comment]
You'll need to create your own transform stream for this. good-squeeze is only for tag based filtering. Check https://github.com/hapijs/good/blob/master/API.md#filtering-using-plugin-configs for an idea of how to do this.

**Comment by mattii** [comment]
Thanks for the hint! 👍
