### ISSUE TITLE
post/patch body params?

### ISSUE THREAD

**Issue by ivanakimov** [hapijs/good-squeeze#27]
Hm, can't seem to get `POST` or `PATCH` body params to log (`GET` requests work fine tho). Am I doing something wrong? Or maybe it's a security issue to log request body?

Configs:
```javascript
...
console: [{
  module: 'good-squeeze',
  name: 'Squeeze',
  args: [{
    error: '*',
    response: '*',
    request: '*'
  }]
}
...
```

Output:
```bash
Tuesday, April 24th 2018, 7:28:18 pm, (random) [response] http://localhost:8080: patch /test {} 200 (14ms)
```

**Comment by erfanio** [comment]
@ivanakimov It looks like you're using `good-console`.
You should open an issue in [good-console](https://github.com/hapijs/good-console), that's the package that does the formatting.

**Comment by ivanakimov** [comment]
My bad :] Posted in https://github.com/hapijs/good-console/issues/105
